FROM openeuler/openeuler:22.03

MAINTAINER TomNewChao<tom_toworld@163.com>

RUN yum update -y && \
    yum install -y vim wget git xz tar make automake autoconf libtool gcc gcc-c++ kernel-devel libmaxminddb-devel pcre-devel openssl openssl-devel tzdata \
        readline-devel libffi-devel python3-devel mariadb-devel python3-pip net-tools.x86_64 iputils

WORKDIR /work/jenkins_bak_cron

COPY . /work/jenkins_bak_cron

RUN cd /work/jenkins_bak_cron && pip3 install -r requirements.txt

RUN git config --global user.email "TomNewChao"
RUN git config --global user.email "tom_toworld@163.com"

ENV LANG=en_US.UTF-8 \
    PYTHONPATH=/work/jenkins_bak_cron

ENTRYPOINT ["python3", "/work/jenkins_bak_cron/jenkins_bak_tools_gitee.py"]